services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-a4$xr2%puj-p))bg6n7_r+m*_=5^jcgm#_@b4)^(rn23q6j36x"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0" # new
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False" # new
      - "DJANGO_SECURE_HSTS_PRELOAD=False" # new
      - "DJANGO_SESSION_COOKIE_SECURE=False"  # new
      - "DJANGO_CSRF_COOKIE_SECURE=False"  # new
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: